# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

array_width = 100
binop_separator = "Back"
brace_style = "PreferSameLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = false
enum_discrim_align_threshold = 0
force_multiline_blocks = true
imports_layout = "Vertical"
indent_style = "Visual" # Правильные отступы у параметров функций
merge_imports = true
reorder_imports = false
reorder_modules = false